### ISSUE TITLE
no pygame module

### ISSUE THREAD

**Issue by Abdelkader-gnichi** [nst/PyGame#1]
hi my friend u are doing great work u have a nice github repo.
i clone ur project and when i run it from my vscode an error shown that the pygame module doesn't exist so how can i make it work can u upload the full source of the project because i can run it an thank u bro

**Comment by m3hrab** [comment]
just go to python/scripts folder, open a command window to this path, type the following:
`C:\python34\scripts> python -m pip install pygame
`
or just open a command window and type the following:
`python -m pip install pygame`

**Comment by Abdelkader-gnichi** [comment]
Ohh ok than pygame it's an external package i thought that it is a messing library ok thank brother
